### ISSUE TITLE
Sudo error when installing action

### ISSUE THREAD

**Issue by walterholohan** [mathieu-bour/setup-sentry-cli#10]
Hi, I am getting the following error when trying to use the 1.1.0 version of this action. mathieu-education/setup-sentry-cli@1.0.0 works perfectly

FYI I am using a self-hosted Github Runner

```
Installing sentry-cli version latest
/usr/bin/sudo cp /Volumes/GithubRunner/_work/_temp/21ade878-4070-43bf-acc9-950995a963a8 /usr/local/bin/sentry-cli
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
Error: Error: The process '/usr/bin/sudo' failed with exit code 1
```

**Comment by matbour** [comment]
Thanks for your report! This is probably related those lines:

https://github.com/mathieu-bour/setup-sentry-cli/blob/5e3d6ec5eb983f9ecd920622b76793ad083be026/src/download.ts#L50-L51

The fix is quite easy, but requires to install the CLI in a non-standard directoy; I'll work that in the next few days.
