### ISSUE TITLE
Please make tag for "1.3.0" in addition to "v1.3.0"

### ISSUE THREAD

**Issue by connorjclark** [mathieu-bour/setup-sentry-cli#18]
```
Error: Unable to resolve action `mathieu-bour/setup-sentry-cli@1.3.0`, unable to find version `1.3.0`
```

https://github.com/connorjclark/ZeldaClassic/actions/runs/4967254394/jobs/8889148638#step:1:35

1) previous tags had both `vx.x.x` and `x.x.x`
2) it'd be nice to have the latest stable in the README: `uses: mathieu-bour/setup-sentry-cli@v1.3.0`

Thanks! :)

**Comment by matbour** [comment]
Hello, thank you for reporting! I just created the [`non-v` 1.3.0 tag ](https://github.com/mathieu-bour/setup-sentry-cli/releases/tag/1.3.0).

Regarding the README, the v1 tag already point to v1.3.0, so I will keep it as it is, since this action will not introduce any breaking change before an hypothetical v2 version.

![image](https://github.com/mathieu-bour/setup-sentry-cli/assets/21281702/c34d93c5-f899-4904-8050-fb1f4bcb8478)
